db:
  host: 127.0.0.1
  port: 4306
  dialect: mysql
  database: reports
  username: root
  password: ""

reports:
  - name: projects
    columns_config: reports/projects.yaml
    groupby: 
      - column: category
    aggregate:
      - type: SUM
        column: jobs
      - type: COUNT
        column: id
    settings:
      dateFormat: 'MM/dd/yyyy'
      pageSize: 10
      export:
        enabled: true
        formats: # List of enabled export formats
          - pdf
          - excel
          - csv
      chart:
        enabled: true
        types: # Available chart types
          - bar
          - line
          - pie
        
  - name: users
    columns_config: reports/users.yaml
    settings:
      dateFormat: 'MM/dd/yyyy'
      pageSize: 10
      export:
        enabled: true
        formats: # List of enabled export formats
          - pdf
          - excel
          - csv
      chart:
        enabled: true
        types: # Available chart types
          - bar
          - line
          - pie

  - name: project_categories
    columns_config: reports/project_categories.yaml
    settings:
      dateFormat: 'MM/dd/yyyy'
      pageSize: 10
      export:
        enabled: true
        formats: # List of enabled export formats
          - pdf
          - excel
          - csv
      chart:
        enabled: true
        types: # Available chart types
          - bar
          - line
          - pie
